openapi: 3.0.0
info:
  title: BMS Points API
  description: API for managing and analyzing Building Management System (BMS) points
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:5000
    description: Development server

paths:
  /api/points/ai-grouping:
    post:
      summary: Group points using AI-based analysis
      description: |
        Groups BMS points into logical device groups using AI-based semantic analysis.
        The grouping can use different strategies including AI, default, or ontology-based approaches.
      tags:
        - Points
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - points
              properties:
                points:
                  type: array
                  items:
                    type: string
                  description: List of point names to group
                  example: ["AHU1_SAT", "AHU1_RAT", "FCU1_SAT"]
                strategy:
                  type: string
                  enum: [ai, default, ontology]
                  default: ai
                  description: The grouping strategy to use
                model:
                  type: string
                  description: Optional AI model override
                  example: "gpt-4o"
      responses:
        '200':
          description: Successful grouping
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  grouped_points:
                    type: object
                    additionalProperties:
                      type: object
                      additionalProperties:
                        type: array
                        items:
                          type: string
                  stats:
                    type: object
                    properties:
                      total_points:
                        type: integer
                        example: 100
                      equipment_types:
                        type: integer
                        example: 5
                      equipment_instances:
                        type: integer
                        example: 20
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "No points data provided"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Error processing points"

  /api/networks:
    post:
      summary: Get available networks
      description: Retrieve available network options for device discovery
      tags:
        - Networks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - apiGateway
                - accessKey
                - secretKey
                - orgId
                - assetId
              properties:
                apiGateway:
                  type: string
                  example: "https://ag-eu2.envisioniot.com"
                accessKey:
                  type: string
                secretKey:
                  type: string
                orgId:
                  type: string
                assetId:
                  type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  networks:
                    type: array
                    items:
                      type: string
                    example: ["192.168.1.0/24", "10.0.0.0/24"]

  /api/devices/discover:
    post:
      summary: Discover devices
      description: Initiate device discovery on selected networks
      tags:
        - Devices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - apiGateway
                - accessKey
                - secretKey
                - orgId
                - assetId
                - networks
              properties:
                apiGateway:
                  type: string
                accessKey:
                  type: string
                secretKey:
                  type: string
                orgId:
                  type: string
                assetId:
                  type: string
                networks:
                  type: array
                  items:
                    type: string
                protocol:
                  type: string
                  default: "bacnet"
      responses:
        '202':
          description: Discovery initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  taskId:
                    type: string
                  status:
                    type: string
                    enum: [processing]

components:
  schemas:
    Point:
      type: object
      properties:
        pointName:
          type: string
          example: "AHU1_SAT"
        pointType:
          type: string
          example: "Temperature"
        unit:
          type: string
          example: "°C"
        description:
          type: string
          example: "Supply Air Temperature"

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
        code:
          type: string

tags:
  - name: Points
    description: Operations for managing BMS points
  - name: Networks
    description: Network discovery and configuration
  - name: Devices
    description: Device management operations

security:
  - ApiKeyAuth: []

externalDocs:
  description: Additional Documentation
  url: http://localhost:5000/docs
